[project]
name = "server-backend"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "lzstring>=1.0.4",
    "markdown>=3.10",
    "requests>=2.32.5",
    "rich>=14.2.0",
    "ujson>=5.11.0",
]
